'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { Flame, Sparkles, Check } from 'lucide-react'
import { Panel } from '@/components/game/panel'
import { ChevronButton } from '@/components/game/chevron-button'
import { InfoTooltip } from '@/components/game/info-tooltip'
import {
  CREEDS,
  PLEDGEABLE_FACTIONS,
  ALLEGIANCE_SIGNATURE,
  FACTION_RIVAL,
  doctrineCostAtLevel,
  type CreedDef,
  type DoctrineDef,
} from '@/lib/game/creed'
import { FACTION_META, type Faction } from '@/lib/faction-meta'
import { adoptCreed, pledgeAllegiance, unlockDoctrine, type getCreedState } from '@/app/actions/creed'
import { cn } from '@/lib/utils'

type CreedState = Awaited<ReturnType<typeof getCreedState>>

interface CreedPanelProps {
  state: CreedState
}

export function CreedPanel({ state }: CreedPanelProps) {
  const router = useRouter()
  const [, startTransition] = useTransition()
  const [busy, setBusy] = useState(false)

  const governor = state.governor
  const devotion = state.projected?.devotion ?? 0
  const devotionRate = state.colony?.devotionRate ?? 0
  const adoptedCreed = CREEDS.find((c) => c.id === governor.creedId) ?? null
  const doctrineLevels = new Map(state.doctrineRows.map((d) => [d.doctrineId, d.level]))

  async function run(action: () => Promise<unknown>, successMsg: string) {
    setBusy(true)
    try {
      await action()
      toast.success(successMsg)
      startTransition(() => router.refresh())
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Action failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Devotion + active modifiers summary */}
      <Panel grid scanline className="flex flex-wrap items-center justify-between gap-4 p-5">
        <div className="flex items-center gap-3">
          <span className="grid size-10 place-items-center border border-devotion/40 bg-devotion/10 clip-chevron-sm">
            <Flame className="size-5 text-devotion" strokeWidth={1.5} aria-hidden="true" />
          </span>
          <div>
            <p className="flex items-center gap-1.5 font-display text-[0.65rem] uppercase tracking-wide text-text-faint">
              Devotion
              <InfoTooltip label="What is Devotion?">
                Devotion is generated by the Sanctum building and spent to consecrate Creed
                doctrines. Build and upgrade your Sanctum to raise the rate.
              </InfoTooltip>
            </p>
            <p className="font-mono text-xl font-medium tabular-nums text-devotion">
              {Math.floor(devotion).toLocaleString()}
            </p>
            <p className="font-mono text-[0.65rem] text-text-faint">
              +{devotionRate.toFixed(2)}/s
            </p>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <ModPill label="Energy" value={state.modifiers.energyMult} />
          <ModPill label="Alloy" value={state.modifiers.alloyMult} />
          <ModPill label="Crystal" value={state.modifiers.crystalMult} />
          <ModPill label="Devotion" value={state.modifiers.devotionMult} />
          <ModPill label="Fleet Atk" value={state.modifiers.fleetAttackMult} />
          <ModPill label="Ship Time" value={state.modifiers.shipTimeMult} invert />
        </div>
      </Panel>

      {/* Allegiance */}
      <section className="flex flex-col gap-3">
        <div className="flex items-center gap-2">
          <h2 className="font-display text-sm font-semibold uppercase tracking-wide text-text-faint">
            Allegiance
          </h2>
          <InfoTooltip label="What is Allegiance?">
            Pledging to a faction grants a permanent economic or military bonus. In combat you gain
            Zeal (+15% attack) against that faction&apos;s rival, but suffer Dissent (-20% attack) if
            you strike your own faction&apos;s holdings.
          </InfoTooltip>
        </div>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {PLEDGEABLE_FACTIONS.map((factionId) => {
            const faction = factionId as Faction
            const meta = FACTION_META[faction]
            const sig = ALLEGIANCE_SIGNATURE[factionId]
            const rival = FACTION_RIVAL[faction]
            const isPledged = governor.allegiance === factionId
            const Icon = meta.icon
            return (
              <Panel
                key={factionId}
                grid
                className={cn(
                  'flex flex-col gap-3 p-4 transition-colors',
                  isPledged ? meta.borderClass : 'border-panel-border',
                )}
              >
                <div className="flex items-center justify-between gap-2">
                  <span className={cn('flex items-center gap-2 font-display text-sm uppercase tracking-wide', meta.textClass)}>
                    <Icon className="size-4" aria-hidden="true" />
                    {meta.label}
                  </span>
                  {isPledged && <Check className={cn('size-4', meta.textClass)} aria-hidden="true" />}
                </div>
                <p className="font-mono text-[0.7rem] leading-relaxed text-bloom">{sig?.label}</p>
                {rival && (
                  <p className="font-mono text-[0.65rem] text-text-faint">
                    Zeal vs {FACTION_META[rival]?.label ?? rival}
                  </p>
                )}
                <ChevronButton
                  variant="concord"
                  size="sm"
                  locked={busy || isPledged}
                  lockedReason={isPledged ? 'Already pledged' : undefined}
                  onClick={() => run(() => pledgeAllegiance(factionId), `Pledged to ${meta.label}`)}
                >
                  {isPledged ? 'Pledged' : 'Pledge'}
                </ChevronButton>
              </Panel>
            )
          })}
        </div>
      </section>

      {/* Creed selection / doctrine tree */}
      <section className="flex flex-col gap-3">
        <div className="flex items-center gap-2">
          <h2 className="font-display text-sm font-semibold uppercase tracking-wide text-text-faint">
            Creed
          </h2>
          <InfoTooltip label="What is a Creed?">
            A Creed is your colony&apos;s belief system. Adopting one grants a signature bonus and
            unlocks a tree of doctrines you consecrate with Devotion for stacking bonuses. Choose
            carefully — your Creed cannot be changed once set.
          </InfoTooltip>
        </div>

        {!adoptedCreed ? (
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            {CREEDS.map((creed) => (
              <CreedChoiceCard
                key={creed.id}
                creed={creed}
                busy={busy}
                onAdopt={() => run(() => adoptCreed(creed.id), `Adopted the ${creed.name}`)}
              />
            ))}
          </div>
        ) : (
          <DoctrineTree
            creed={adoptedCreed}
            doctrineLevels={doctrineLevels}
            devotion={devotion}
            busy={busy}
            onUnlock={(id, name, level) =>
              run(() => unlockDoctrine(id), `${name} consecrated to level ${level}`)
            }
          />
        )}
      </section>
    </div>
  )
}

function ModPill({ label, value, invert = false }: { label: string; value: number; invert?: boolean }) {
  if (Math.abs(value - 1) < 0.001) return null
  // For "lower is better" stats (ship time), a value < 1 is positive.
  const pct = Math.round((value - 1) * 100)
  const positive = invert ? pct < 0 : pct > 0
  return (
    <span
      className={cn(
        'border px-2 py-1 font-mono text-[0.65rem] tabular-nums clip-chevron-sm',
        positive ? 'border-bloom/40 bg-bloom/10 text-bloom' : 'border-obsidian/40 bg-obsidian/10 text-obsidian',
      )}
    >
      {label} {pct > 0 ? '+' : ''}{pct}%
    </span>
  )
}

function CreedChoiceCard({
  creed,
  busy,
  onAdopt,
}: {
  creed: CreedDef
  busy: boolean
  onAdopt: () => void
}) {
  const Icon = creed.icon
  return (
    <Panel grid className={cn('flex flex-col gap-3 p-5', creed.borderClass)}>
      <div className="flex items-center gap-3">
        <span className={cn('grid size-10 place-items-center border clip-chevron-sm', creed.borderClass, creed.bgClass)}>
          <Icon className={cn('size-5', creed.colorClass)} strokeWidth={1.5} aria-hidden="true" />
        </span>
        <div>
          <h3 className={cn('font-display text-base font-semibold uppercase tracking-wide', creed.colorClass)}>
            {creed.name}
          </h3>
          <p className="font-mono text-[0.65rem] uppercase tracking-wide text-text-faint">
            {creed.epithet}
          </p>
        </div>
      </div>
      <p className="font-mono text-xs leading-relaxed text-text-dim">{creed.description}</p>
      <div className="flex items-center gap-1.5 font-mono text-[0.7rem] text-bloom">
        <Sparkles className="size-3.5" aria-hidden="true" />
        Signature: {creed.signatureLabel}
      </div>
      <ul className="flex flex-col gap-1 border-t border-panel-border/60 pt-2">
        {creed.doctrines.map((d) => (
          <li key={d.id} className="flex items-center gap-1.5 font-mono text-[0.65rem] text-text-faint">
            <span className="size-1 rounded-full bg-text-faint" aria-hidden="true" />
            {d.name}
          </li>
        ))}
      </ul>
      <ChevronButton variant="alloy" locked={busy} onClick={onAdopt}>
        <Flame className="size-3.5" aria-hidden="true" />
        Adopt this Creed
      </ChevronButton>
    </Panel>
  )
}

function DoctrineTree({
  creed,
  doctrineLevels,
  devotion,
  busy,
  onUnlock,
}: {
  creed: CreedDef
  doctrineLevels: Map<string, number>
  devotion: number
  busy: boolean
  onUnlock: (id: string, name: string, level: number) => void
}) {
  const Icon = creed.icon
  return (
    <div className="flex flex-col gap-4">
      <Panel grid className={cn('flex items-center gap-3 p-4', creed.borderClass, creed.bgClass)}>
        <Icon className={cn('size-6', creed.colorClass)} strokeWidth={1.5} aria-hidden="true" />
        <div>
          <h3 className={cn('font-display text-base font-semibold uppercase tracking-wide', creed.colorClass)}>
            {creed.name}
          </h3>
          <p className="font-mono text-[0.7rem] text-bloom">Signature · {creed.signatureLabel}</p>
        </div>
      </Panel>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        {creed.doctrines.map((doctrine) => (
          <DoctrineCard
            key={doctrine.id}
            doctrine={doctrine}
            level={doctrineLevels.get(doctrine.id) ?? 0}
            devotion={devotion}
            busy={busy}
            colorClass={creed.colorClass}
            onUnlock={onUnlock}
          />
        ))}
      </div>
    </div>
  )
}

function DoctrineCard({
  doctrine,
  level,
  devotion,
  busy,
  colorClass,
  onUnlock,
}: {
  doctrine: DoctrineDef
  level: number
  devotion: number
  busy: boolean
  colorClass: string
  onUnlock: (id: string, name: string, level: number) => void
}) {
  const maxed = level >= doctrine.maxLevel
  const targetLevel = level + 1
  const cost = maxed ? 0 : doctrineCostAtLevel(doctrine, targetLevel)
  const affordable = devotion >= cost

  return (
    <Panel grid className="flex flex-col gap-3 p-4">
      <div className="flex items-start justify-between gap-2">
        <h4 className={cn('font-display text-sm font-semibold uppercase tracking-wide', colorClass)}>
          {doctrine.name}
        </h4>
        <span className="font-mono text-[0.65rem] tabular-nums text-text-faint">
          LVL {level}/{doctrine.maxLevel}
        </span>
      </div>
      <p className="font-mono text-[0.7rem] leading-relaxed text-text-dim">{doctrine.description}</p>

      {/* Level pips */}
      <div className="flex gap-1" aria-hidden="true">
        {Array.from({ length: doctrine.maxLevel }).map((_, i) => (
          <span
            key={i}
            className={cn(
              'h-1.5 flex-1 rounded-full',
              i < level ? 'bg-devotion' : 'bg-panel-border',
            )}
          />
        ))}
      </div>

      {maxed ? (
        <div className="flex items-center justify-center gap-1.5 border border-bloom/40 bg-bloom/5 py-2 font-mono text-[0.65rem] uppercase tracking-wide text-bloom clip-chevron-sm">
          <Check className="size-3.5" aria-hidden="true" />
          Fully Consecrated
        </div>
      ) : (
        <ChevronButton
          variant="alloy"
          size="sm"
          locked={busy || !affordable}
          lockedReason={!affordable ? `Needs ${cost.toLocaleString()} Devotion` : undefined}
          onClick={() => onUnlock(doctrine.id, doctrine.name, targetLevel)}
        >
          <Flame className="size-3.5" aria-hidden="true" />
          {level === 0 ? 'Consecrate' : 'Deepen'} · {cost.toLocaleString()}
        </ChevronButton>
      )}
    </Panel>
  )
}
